theme: jekyll-theme-some
title: Semih Güzelel
author:
  name: Semih Güzelel
  email: semihguzelel@gmail.com
description: Semih Güzelel, Software Developer
github_username: smhgzll
linkedin_username: semihguzelel
year: 2022